apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: monolith
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: monolith
    spec:
      containers:
        - name: monolith
          image: kelseyhightower/monolith:1.0.0
          args:
            - "-http=0.0.0.0:80"
            - "-health=0.0.0.0:81"
            - "-secret=secret"
          ports:
          - containerPort: 80
